In [ ]:
a=10
b=20
a,b=b,a
print("a is",a)
print("b is",b)

a is 20
b is 10

In [ ]:
a=10
b=20
temp=a
a=b
b=temp
print(a)
print(b)

20
10

In [ ]:
marks = int(input("Enter student marks: "))
if marks < 35:
    print("He is fail")
elif marks < 60:
    print("He is pass")
elif marks < 80:
    print("He is 1st class")
elif marks <= 100:
    print("He is distinction")
else:
  print("enter a currect marks")

Enter student marks: 70
He is 1st class

In [ ]:
for i in range(10,0,-1):
  print(i)

10
9
8
7
6
5
4
3
2
1

In [ ]:
for i in range(10):
  print(i)

0
1
2
3
4
5
6
7
8
9

In [ ]:
for i in "python":
  print(i)

p
y
t
h
o
n

In [ ]:
for i in "python":
  print(i,end="")

python

In [ ]:
i = 50
while i <= 600:
    print(i)
    i += 75

50
125
200
275
350
425
500
575

In [ ]:
i = 600
while i >= 50:
    print(i)
    i -= 75

600
525
450
375
300
225
150
75

In [ ]:
i = 786

while i > 0:
    d = i % 10
    print(d)
    i = i // 10

6
8
7

In [ ]:
n = int(input("Enter a number: "))
temp = n
b = 0

while n > 0:
    d = n % 10
    b = b * 10 + d
    n = n // 10

if temp == b:
    print("Palindrome")
else:
    print("Not Palindrome")

Enter a number: 858
Palindrome

In [ ]:
n = int(input("Enter a number: "))
count = 0
# if the start and end point are same it not generate any number
for i in range(1, n + 1):
    if n % i == 0:
        count += 1

if count == 2:
    print("Prime number")
else:
    print("Not a prime number")

Enter a number: 5
Prime number

In [ ]:
n = int(input("How many prime numbers do you want? "))

count = 0
num = 2

while count < n:
    i = 2
    is_prime = True

    while i < num:
        if num % i == 0:
            is_prime = False
            break
        i += 1

    if is_prime:
        print(num)
        count += 1

    num += 1

How many prime numbers do you want? 5
2
3
5
7
11

In [ ]:
n = int(input("Enter a number: "))

for num in range(2, n):
    count = 0

    for i in range(1, num + 1):
        if num % i == 0:
            count += 1

    if count == 2:
        print(num)

Enter a number: 5
2
3

In [ ]:
for i in range(10):
  if i==5:
    continue
  print(i)

0
1
2
3
4
6
7
8
9

In [ ]:
for i in range(10):
  if i==5:
    break
  print(i)

0
1
2
3
4

In [ ]:
for i in range(10,0,-1):
  if i==6:
    continue
  print(i)

10
9
8
7
5
4
3
2
1

In [ ]:
a=["Abhi",23,18.92]
a[0]="sachi"
a[2]="Raghavendra"
print(a)

['sachi', 23, 'Raghavendra']

## **list**

| Method      | Use                                 | Example           |
| ----------- | ----------------------------------- | ----------------- |
| `append()`  | Adds element at the end             | `a.append(50)`    |
| `insert()`  | Adds element at a specific position | `a.insert(1, 50)` |
| `remove()`  | Removes specified element           | `a.remove(20)`    |
| `pop()`     | Removes an element                  | `a.pop()`         |
| `clear()`   | Removes all elements                | `a.clear()`       |
| `sort()`    | Sorts the list                      | `a.sort()`        |
| `reverse()` | Reverses the list                   | `a.reverse()`     |
| `index()`   | Finds position of an element        | `a.index(20)`     |
| `count()`   | Counts an element                   | `a.count(20)`     |
| `copy()`    | Copies the list                     | `b = a.copy()`    |
| `extend()`  | Adds another list                   | `a.extend(b)`     |

In [ ]:
a=[2,4,6,7,8]

a.append(10)
print(a)

a.insert(2,5)
print(a)

a.remove(7)
print(a)

a.pop()
print(a)

a.clear()
print(a)

[2, 4, 6, 7, 8, 10]
[2, 4, 5, 6, 7, 8, 10]
[2, 4, 5, 6, 8, 10]
[2, 4, 5, 6, 8]
[]

In [ ]:
a = [10, 20, 30, 40]

# append()
a.append(50)
print("append:", a)

# insert()
a.insert(1, 15)
print("insert:", a)

# remove()
a.remove(30)
print("remove:", a)

# pop()
a.pop()
print("pop:", a)

# sort()
a.sort()
print("sort:", a)

# reverse()
a.reverse()
print("reverse:", a)

# index()
print("index of 20:", a.index(20))

# count()
print("count of 20:", a.count(20))

# copy()
b = a.copy()
print("copy:", b)

# extend()
a.extend([60, 70])
print("extend:", a)

# clear()
a.clear()
print("clear:", a)

# **tuple**

tuple is also order collection  of element but it is a immuteble  and con't change
| Method      | Meaning                           | Result |
| ----------- | --------------------------------- | -----: |
| `count(4)`  | Counts how many times `4` appears |    `1` |
| `index(10)` | Finds the index/position of `10`  |    `4` |

In [ ]:
a = (2, 4, 8, 9, 10)

print(a.count(4))
print(a.index(10))

1
4

set is a muteble

In [ ]:
a = {10, 20, 30, 20, 10}
print(a)

{10, 20, 30}

## **set**

Set is a collection of unique elements.
It is mutable, so we can add and remove elements.
Set is unordered, so it does not have a fixed position/index.
Duplicate values are automatically removed.
Set does not support indexing or slicing.
Set is written using {}.
Empty set is created using set().

| Method                          | Use                                       |
| ------------------------------- | ----------------------------------------- |
| `add()`                         | Add an element                            |
| `clear()`                       | Remove all elements                       |
| `copy()`                        | Copy the set                              |
| `difference()`                  | Find elements in first set but not second |
| `difference_update()`           | Remove common elements                    |
| `discard()`                     | Remove an element without error           |
| `intersection()`                | Find common elements                      |
| `intersection_update()`         | Keep only common elements                 |
| `isdisjoint()`                  | Check if there are no common elements     |
| `issubset()`                    | Check if one set is inside another        |
| `issuperset()`                  | Check if one set contains another         |
| `pop()`                         | Remove an arbitrary element               |
| `remove()`                      | Remove an element                         |
| `symmetric_difference()`        | Find non-common elements                  |
| `symmetric_difference_update()` | Update with non-common elements           |
| `union()`                       | Combine two sets                          |
| `update()`                      | Add multiple elements                     |

In [ ]:
a = {10, 20, 30}
b = {20, 30, 40}

# add()
a.add(50)
print("add:", a)

# update()
a.update([60, 70])
print("update:", a)

# remove()
a.remove(10)
print("remove:", a)

# discard()
a.discard(100)
print("discard:", a)

# union()
print("union:", a.union(b))

# intersection()
print("intersection:", a.intersection(b))

# difference()
print("difference:", a.difference(b))

# symmetric_difference()
print("symmetric difference:", a.symmetric_difference(b))

# isdisjoint()
print("isdisjoint:", a.isdisjoint(b))

# issubset()
c = {20, 30}
print("issubset:", c.issubset(b))

# issuperset()
print("issuperset:", b.issuperset(c))

# copy()
d = a.copy()
print("copy:", d)

# pop()
a.pop()
print("pop:", a)

# clear()
a.clear()
print("clear:", a)

add: {10, 20, 50, 30}
update: {70, 10, 50, 20, 60, 30}
remove: {70, 50, 20, 60, 30}
discard: {70, 50, 20, 60, 30}
union: {50, 20, 70, 40, 60, 30}
intersection: {20, 30}
difference: {50, 60, 70}
symmetric difference: {70, 40, 50, 60}
isdisjoint: False
issubset: True
issuperset: True
copy: {50, 20, 70, 60, 30}
pop: {50, 20, 60, 30}
clear: set()

# **Dictionary**

used to store the key value



| Method         | Definition                                               | Example                   |
| -------------- | -------------------------------------------------------- | ------------------------- |
| `clear()`      | Removes all items from the dictionary.                   | `d.clear()`               |
| `copy()`       | Creates a copy of the dictionary.                        | `d2 = d.copy()`           |
| `fromkeys()`   | Creates a dictionary with specified keys.                | `dict.fromkeys(keys)`     |
| `get()`        | Returns the value of a specified key.                    | `d.get("name")`           |
| `items()`      | Returns all key-value pairs.                             | `d.items()`               |
| `keys()`       | Returns all keys.                                        | `d.keys()`                |
| `pop()`        | Removes an item using its key.                           | `d.pop("age")`            |
| `popitem()`    | Removes the last inserted key-value pair.                | `d.popitem()`             |
| `setdefault()` | Returns the value of a key; adds it if it doesn't exist. | `d.setdefault("age", 20)` |
| `update()`     | Adds or updates key-value pairs.                         | `d.update({"age": 21})`   |
| `values()`     | Returns all values.                                      | `d.values()`              |

In [ ]:
d = {
    "name": "Ravi",
    "age": 20,
    "marks": 85
}

# clear()
d1 = d.copy()
d1.clear()
print("clear:", d1)

# copy()
d2 = d.copy()
print("copy:", d2)

# fromkeys()
keys = ["name", "age", "marks"]
d3 = dict.fromkeys(keys, 0)
print("fromkeys:", d3)

# get()
print("get:", d.get("name"))

# items()
print("items:", d.items())

# keys()
print("keys:", d.keys())

# values()
print("values:", d.values())

# pop()
d4 = d.copy()
d4.pop("age")
print("pop:", d4)

# popitem()
d5 = d.copy()
d5.popitem()
print("popitem:", d5)

# setdefault()
d6 = d.copy()
d6.setdefault("city", "Shivamogga")
print("setdefault:", d6)

# update()
d7 = d.copy()
d7.update({"age": 21})
print("update:", d7)

clear: {}
copy: {'name': 'Ravi', 'age': 20, 'marks': 85}
fromkeys: {'name': 0, 'age': 0, 'marks': 0}
get: Ravi
items: dict_items([('name', 'Ravi'), ('age', 20), ('marks', 85)])
keys: dict_keys(['name', 'age', 'marks'])
values: dict_values(['Ravi', 20, 85])
pop: {'name': 'Ravi', 'marks': 85}
popitem: {'name': 'Ravi', 'age': 20}
setdefault: {'name': 'Ravi', 'age': 20, 'marks': 85, 'city': 'Shivamogga'}
update: {'name': 'Ravi', 'age': 21, 'marks': 85}

# **string**

String is a collection (group) of characters enclosed in single quotes (' '), double quotes (" "), or triple quotes (''' ''' or """ """).

In [ ]:
s = "hello python world"

# 1. isupper()
print(s.isupper())

# 2. capitalize()
print(s.capitalize())

# 3. casefold()
print(s.casefold())

# 4. center()
print(s.center(30, "-"))

# 5. count()
print(s.count("o"))

# 6. encode()
print(s.encode())

# 7. endswith()
print(s.endswith("world"))

# 8. expandtabs()
text = "Hello\tPython"
print(text.expandtabs(4))

# 9. find()
print(s.find("python"))

# 10. format()
name = "Raghavendra"
age = 19
print("My name is {} and I am {} years old".format(name, age))

# 11. format_map()
data = {"name": "Raghavendra", "age": 19}
print("My name is {name} and I am {age} years old".format_map(data))

# 12. index()
print(s.index("python"))

False
Hello python world
hello python world
------hello python world------
3
b'hello python world'
True
Hello   Python
6
My name is Raghavendra and I am 19 years old
My name is Raghavendra and I am 19 years old
6


# **Python String Methods**

| Method         | Definition                                      | Example                                  |
| -------------- | ----------------------------------------------- | ---------------------------------------- |
| `capitalize()` | Converts the first character to uppercase       | `"python".capitalize()` → `Python`       |
| `casefold()`   | Converts string to lowercase                    | `"PYTHON".casefold()` → `python`         |
| `lower()`      | Converts all characters to lowercase            | `"PYTHON".lower()` → `python`            |
| `upper()`      | Converts all characters to uppercase            | `"python".upper()` → `PYTHON`            |
| `title()`      | Converts first letter of each word to uppercase | `"hello world".title()` → `Hello World`  |
| `swapcase()`   | Changes uppercase to lowercase and vice versa   | `"PyThOn".swapcase()` → `pYtHoN`         |
| `count()`      | Counts occurrences of a character/substring     | `"banana".count("a")` → `3`              |
| `find()`       | Returns position of first occurrence            | `"python".find("t")` → `2`               |
| `rfind()`      | Returns position of last occurrence             | `"banana".rfind("a")` → `5`              |
| `index()`      | Returns position of first occurrence            | `"python".index("t")` → `2`              |
| `rindex()`     | Returns position of last occurrence             | `"banana".rindex("a")` → `5`             |
| `replace()`    | Replaces part of a string                       | `"I like Java".replace("Java","Python")` |
| `split()`      | Splits string into a list                       | `"a b c".split()` → `['a','b','c']`      |
| `rsplit()`     | Splits from the right side                      | `"a-b-c".rsplit("-",1)`                  |
| `splitlines()` | Splits string at line breaks                    | `"a\nb".splitlines()`                    |
| `join()`       | Joins elements into a string                    | `"-".join(["a","b"])` → `a-b`            |
| `strip()`      | Removes spaces from both sides                  | `" hello ".strip()`                      |
| `lstrip()`     | Removes spaces from left side                   | `" hello".lstrip()`                      |
| `rstrip()`     | Removes spaces from right side                  | `"hello ".rstrip()`                      |
| `startswith()` | Checks beginning of string                      | `"Python".startswith("Py")` → `True`     |
| `endswith()`   | Checks ending of string                         | `"Python".endswith("on")` → `True`       |
| `center()`     | Centers the string                              | `"Hi".center(10)`                        |
| `ljust()`      | Left-aligns the string                          | `"Hi".ljust(10)`                         |
| `rjust()`      | Right-aligns the string                         | `"Hi".rjust(10)`                         |
| `zfill()`      | Adds zeros to the beginning                     | `"25".zfill(5)` → `00025`                |
| `format()`     | Formats values inside a string                  | `"My age is {}".format(18)`              |
| `format_map()` | Formats using a dictionary                      | `"Hi {name}".format_map({"name":"Ram"})` |
| `translate()`  | Replaces characters using a translation table   | `"abc".translate(...)`                   |
| `maketrans()`  | Creates a translation table                     | `str.maketrans("abc","123")`             |
| `expandtabs()` | Replaces tabs with spaces                       | `"a\tb".expandtabs(4)`                   |
| `encode()`     | Converts string into bytes                      | `"hello".encode()`                       |




# **Methods that Check a String**

These methods return True or False.

| Method           | Definition                                  | Example                            |
| ---------------- | ------------------------------------------- | ---------------------------------- |
| `isalpha()`      | Checks whether all characters are alphabets | `"Hello".isalpha()` → `True`       |
| `isdigit()`      | Checks whether all characters are digits    | `"123".isdigit()` → `True`         |
| `isdecimal()`    | Checks decimal characters                   | `"123".isdecimal()` → `True`       |
| `isnumeric()`    | Checks numeric characters                   | `"123".isnumeric()` → `True`       |
| `isalnum()`      | Checks alphabets or numbers                 | `"abc123".isalnum()` → `True`      |
| `isspace()`      | Checks whether all are spaces               | `"   ".isspace()` → `True`         |
| `islower()`      | Checks whether characters are lowercase     | `"hello".islower()` → `True`       |
| `isupper()`      | Checks whether characters are uppercase     | `"HELLO".isupper()` → `True`       |
| `istitle()`      | Checks title case                           | `"Hello World".istitle()` → `True` |
| `isidentifier()` | Checks valid Python identifier              | `"name".isidentifier()` → `True`   |
| `isascii()`      | Checks ASCII characters                     | `"Hello".isascii()` → `True`       |
| `isprintable()`  | Checks printable characters                 | `"Hello".isprintable()` → `True`   |

Funtion

slising ,
s="python program"
s[1:6:1]
op=ython

s[ : : ]->same order
s[ : :-1]->revers

In [ ]:
a=[10,20,[2,6,8,[12,16,18]]]
print(a[2][2])

8

Funtions in pythone

A function in Python is a reusable block of code that performs a specific task.




---

In [ ]:
def add(a, b, c):
    print(a + b + c)

add(10, 20, 30)

60

In [ ]:
def add1(a,b,c):
  print(a+b+c)
b=add1(10,20,30)
print(b)

60
None

In [ ]:
def add3(a,b,c):
  return(a+b+c)
c=add3(10,20,30)
print(c)

60

types of argument

In [ ]:
def student (name,age):
  print("my name is ",name)
  print("my name is",age)
student("rohit",24)#position argument

my name is  rohit
my name is 24

In [ ]:
def student (name,age):
  print("my name is ",name)
  print("my name is",age)
student(age=24,name="rohit")#key argument

my name is  rohit
my name is 24

In [ ]:
def number(*a):
  print(a)
number(1, 2, 3, 5, 7, 9, 8, 9)#veriable lenth argument

(1, 2, 3, 5, 7, 9, 8, 9)

In [ ]:
def my_fun(**r):
  print(type(r))
  for i in r.items():
    print(i)
  for i in r.values():
    print(i)
my_fun(last="bye",name="rohit",first="hi")#Keyword Variable-Length Arguments

<class 'dict'>
('last', 'bye')
('name', 'rohit')
('first', 'hi')
bye
rohit
hi

In [ ]:
def prime():
    n = int(input("Enter no: "))
    count = 0
    for i in range(1, n + 1):
        if n % i == 0:
            count += 1
    if count == 2:
        print("Prime no")
    else:
        print("it is not a prime no")
prime()

Enter a number: 5
Prime number

In [ ]:
def largest(a, b, c):
    if a > b and a > c:
        print(a, "is largest")
    elif b > a and b > c:
        print(b, "is largest")
    else:
        print(c, "is largest")
largest(10, 25, 15)

25 is largest

In [ ]:
a=lambda x:x**3
a(2)

8

In [ ]:
a = int(input("Enter 1st no: "))
b = int(input("Enter 2nd no: "))
c = int(input("Enter 3rd no: "))

largest = a if a > b and a > c else b if b > c else c

print("Largest no is:", largest)

In [ ]:
def myfun(**kwargs):
  for key,value in kwargs.items():
    print(f"{key}:{value}")
myfun (first="hello",secound="hi",third="bye")

first:hello
secound:hi
third:bye

In [ ]:
list(map(lambda x:x**2,[1,2,3,4,5]))

[1, 4, 9, 16, 25]

In [ ]:
list(map(lambda x:x+500,[10000,25000,35000,40000,50000]))

[10000, 25000, 35000, 40000, 50000]

In [ ]:
list(filter(lambda x:x>5,[1,2,3,4,5,6,7,8]))

[6, 7, 8]

In [ ]:
n=["Ramma","beema","sooma","marma"]
for i,n in enumerate(n,start=1):
  print(i,n)

1 Ramma
2 beema
3 sooma
4 marma

In [ ]:
def myfun(**kwargs):
  for key,value in kwarge.items():
    print(f"{key}:{value}")
my_fun(first="hello",second="hi",third="bye")

<class 'dict'>
('first', 'hello')
('second', 'hi')
('third', 'bye')
hello
hi
bye

# object orineted programing language

## Local and Global Variables

In Python, the scope of a variable refers to the region of the code where a variable is accessible.

*   **Global Variables**: Variables declared outside of any function are considered global variables. They can be accessed from anywhere in the program, both inside and outside functions.

*   **Local Variables**: Variables declared inside a function are local variables. They are only accessible within the function where they are defined. Once the function finishes execution, the local variables are destroyed.

In [ ]:
# Global variable
global_var = "I am a global variable"

def my_function():
    # Local variable
    local_var = "I am a local variable"
    print(f"Inside the function: {global_var}") # Accessing global_var
    print(f"Inside the function: {local_var}")  # Accessing local_var

my_function()

print(f"Outside the function: {global_var}") # Accessing global_var
# The following line would cause an error because local_var is not defined in the global scope:
# print(f"Outside the function: {local_var}")

In [ ]:
class student:
  def __init__(self, name, house):
    if not name:
      raise ValueError("missing name")
    if house not in ["bangalure", "tumkuri", "hubli"]:
      raise ValueError("in valid house")
    self.name = name
    self.house = house

## Method Overloading

Method overloading refers to having multiple methods with the same name but different parameters within the same class. Python does **not** support method overloading in the traditional sense (like Java or C++), where you can define two methods with the same name but different numbers or types of arguments.

However, you can achieve similar functionality using techniques like:

1.  **Default arguments**: Provide default values for parameters, making them optional.
2.  **Variable-length arguments (`*args`)**: Allow a function to accept an arbitrary number of positional arguments.
3.  **Keyword arguments (`**kwargs`)**: Allow a function to accept an arbitrary number of keyword arguments.

Let's demonstrate with default arguments, which is the most common way to handle varying arguments for a single function name in Python.

In [ ]:
class Calculator:
    def add(self, a, b=0, c=0):
        if b == 0 and c == 0:
            print(f"Adding one number: {a}")
            return a
        elif c == 0:
            print(f"Adding two numbers: {a} + {b}")
            return a + b
        else:
            print(f"Adding three numbers: {a} + {b} + {c}")
            return a + b + c

# Creating an instance of the Calculator class
calc = Calculator()

# Calling the add method with different numbers of arguments
print(f"Result (one argument): {calc.add(10)}")
print(f"Result (two arguments): {calc.add(10, 20)}")
print(f"Result (three arguments): {calc.add(10, 20, 30)}")

## Method Overriding

Method overriding occurs when a subclass (child class) provides its own specific implementation for a method that is already defined in its superclass (parent class). This allows a subclass to change the behavior of an inherited method, while keeping the same method signature (name, number of arguments).

When a method is called on an object, Python checks the object's class first. If the method is found there, it's executed. If not, Python looks up the inheritance chain to the parent class, and so on, until the method is found. This is how the overridden method in the subclass takes precedence.

In [ ]:
class Animal:
    def speak(self):
        print("Animal makes a sound")

class Dog(Animal):
    def speak(self):
        print("Dog barks")

class Cat(Animal):
    def speak(self):
        print("Cat meows")

# Create instances
animal = Animal()
dog = Dog()
cat = Cat()

# Call the speak method
animal.speak() # Output: Animal makes a sound
dog.speak()    # Output: Dog barks
cat.speak()    # Output: Cat meows

## Constructors (`__init__` method)

A constructor in Python is a special method called `__init__`. It is automatically called when you create a new object (instance) of a class. The primary purpose of a constructor is to initialize the attributes (variables) of the object.

It allows you to set up the initial state of the object right when it's created. The `self` parameter refers to the instance of the class itself.

In [ ]:
class calculator:
  def add(self, name1, name2):
    result = name1 + name2
    print(f"The result of addition is: {result}")

  def subtract(self, name1, name2):
    result = name1 - name2
    print(f"The result of subtraction is: {result}")

# Create an instance of the calculator class outside the class definition
my_calculator = calculator()
my_calculator.add(15, 7)
my_calculator.subtract(15, 7)

The result of addition is: 22
The result of subtraction is: 8

In [ ]:
class Employee:

    company = "TCS"
    def employee_details(self, empid, name, salary):
        print("employee id:", empid)
        print("employee name:", name)
        print("employee salary:", salary)
e3 = Employee()
e3.employee_details(101, "Rohit", 30000)
print("Company:", e3.company)

In [ ]:
class calculator:
  def __init__(self,num1,num2):
    self.num1=num1
    self.num2=num2
  def add(self):
    result = self.num1 + self.num2
    print("the addition is:",result)
  def sub(self):
    result = self.num1 - self.num2
    print("the subtraction is:",result)
my_calculator = calculator(10, 5)
my_calculator.add()
my_calculator.sub()

the addition is: 15
the subtraction is: 5

In [ ]:
class Student:

    def __init__(self, stu_id, name, age, marks, village, college,
                class_name, section, rollno, gender, mobile, insta, email):
        self.stu_id = stu_id
        self.name = name
        self.age = age
        self.marks = marks
        self.village = village
        self.college = college
        self.class_name = class_name
        self.section = section
        self.rollno = rollno
        self.gender = gender
        self.mobile = mobile
        self.insta = insta
        self.email = email

    def details(self):
        print("\nStudent Details")
        print("ID:", self.stu_id)
        print("Name:", self.name)
        print("Age:", self.age)
        print("Marks:", self.marks)
        print("Village:", self.village)
        print("College:", self.college)
        print("Class:", self.class_name)
        print("Section:", self.section)
        print("Roll No:", self.rollno)
        print("Gender:", self.gender)
        print("Mobile:", self.mobile)
        print("Instagram:", self.insta)
        print("Email:", self.email)


students = [] # To store multiple student objects

# Define a list of prompts for each student detail
student_prompts = [
    "Enter ID: ", "Enter Name: ", "Enter Age: ", "Enter Marks: ",
    "Enter Village: ", "Enter College: ", "Enter Class: ", "Enter Section: ",
    "Enter Roll No: ", "Enter Gender: ", "Enter Mobile: ", "Enter Instagram ID: ",
    "Enter Email: "
]

for i in range(2): # Reduced to 2 iterations for brevity in example
    print("\nEnter Student", i + 1, "Details")
    student_data = []
    for prompt in student_prompts:
        student_data.append(input(prompt))

    # Create a Student object using the constructor with unpacked data
    s = Student(*student_data)
    students.append(s)

# Display details for all created students
for s in students:
    s.details()

Enter Student 1 Details

Enter Student 2 Details

# Inheritence (types)

Python supports several types of inheritance, allowing a class to inherit attributes and methods from one or more other classes. This promotes code reusability and helps establish a relationship between different classes.

Here are the main types of inheritance demonstrated:

1.  **Single Inheritance**:
    *   A class inherits from a single base class.
    *   Example: `Child` class inheriting from `Parent` class.

2.  **Multiple Inheritance**:
    *   A class inherits from multiple base classes.
    *   Example: `Child` class inheriting from both `Father` and `Mother` classes.

3.  **Multilevel Inheritance**:
    *   A class inherits from a base class, and then another class inherits from that derived class. It forms a chain of inheritance.
    *   Example: `Child` inherits from `Father`, and `Father` inherits from `Grandfather`.

4.  **Hierarchical Inheritance**:
    *   Multiple classes inherit from a single base class.
    *   Example: `Boys` and `Girls` classes both inheriting from the `Class` class.

5.  **Hybrid Inheritance**:
    *   A combination of two or more types of inheritance. It can involve a mix of single, multiple, or multilevel inheritance structures.
    *   Example: Class `D` inherits from `B` and `C`, while `B` and `C` both inherit from `A`.

In [ ]:
# single inheritence
class Parent:
    def show_parent(self):
        print("This is Parent")
class Child(Parent):
    def show_child(self):
        print("This is Child")
obj = Child()
obj.show_parent()
obj.show_child()

In [ ]:
#multiple inheritence
class Father:
    def father(self):
        print("Father")
class Mother:
    def mother(self):
        print("Mother")
class Child(Father, Mother):
    def child(self):
        print("Child")
obj = Child()
obj.father()
obj.mother()
obj.child()

In [ ]:
#multilevel inheritence
class Grandfather:
    def grandfather(self):
        print("Grandfather")
class Father(Grandfather):
    def father(self):
        print("Father")
class Child(Father):
    def child(self):
        print("Child")
obj = Child()
obj.grandfather()
obj.father()
obj.child()

In [ ]:
#hierarchical inheritance
class Class:
    def classroom(self):
        print("This is the class")
class Boys(Class):
    def boys(self):
        print("Boys are studying")
class Girls(Class):
    def girls(self):
        print("Girls are studying")
b = Boys()
b.classroom()
b.boys()
g = Girls()
g.classroom()
g.girls()

In [ ]:
#hybrid inheritence
class A:
    def show_a(self):
        print("A")
class B(A):
    def show_b(self):
        print("B")
class C(A):
    def show_c(self):
        print("C")
class D(B, C):
    def show_d(self):
        print("D")
obj = D()
obj.show_a()
obj.show_b()
obj.show_c()
obj.show_d()

A
B
C
D

In [ ]:
class Emp:
    def show(self):
        print("Method from E")
class Stu(Emp):
    def show(self):
        print("Student details")
obj = Stu()
obj.show()

Student details

In [ ]:
class Emp:
    def show(self):
        print("Method from E")


class Stu(Emp):
    def show(self):
        print("Student details")


obj = Stu()
obj.show()

Student details

In [ ]:
class stu:
  def __init__(self):
    self.name="Ram"
    self.age=20
    self.__marks=87
  s1=stu()
  print(s1.name)
  print(s1.age)
  print(s1.__marks)

Ram
20
87

In [ ]:
class atm:
    def __init__(self):
        self.__pin = ""
        self.__balance = 0
    def get_balance(self):
        return self.__balance
    def set_balance(self, new_value):
        if type(new_value) == int:
            self.__balance = new_value
        else:
            print("beta bohot maarenga")
class Person:
    def __init__(self, name, age):
        self.__name = name
        self.age = age
p1 = Person("john", 21)
p2 = Person("poiyu", 18)
p3 = Person("raju", 32)

L=[p1,p2,p3]
print(L)

[<__main__.Person object at 0x787baee5ab40>, <__main__.Person object at 0x787bae6c9a00>, <__main__.Person object at 0x787bae6c9040>]

# encapsulation

In [ ]:
class Emp:
    def __init__(self, salary):
        self.__salary = salary

    def get_salary(self):
        return self.__salary

    def set_salary(self, salary):
        if salary >= 0:
            self.__salary = salary
        else:
            print("Salary cannot be negative")
# Create object
e1 = Emp(30000)
# Get salary
print(e1.get_salary())
# Change salary
e1.set_salary(40000)
# Get updated salary
print(e1.get_salary())
# Try negative salary
e1.set_salary(-5000)

30000
40000
Salary cannot be negative

In [ ]:
def DivideAmount(total, price):
    try:
        result = total / price

    except ZeroDivisionError:
        print("Zero Division Error")

    except TypeError:
        print("Type Error")

    else:
        print(result)

    finally:
        print("Finally")


DivideAmount(100, 0)

# numpy and pandas

In [ ]:
lst=[20,30,40,60,70]
print(max(lst))
print(sum(lst))

70
220

In [ ]:
import numpy as np
sales=np.array([100,150,300,400,600])
print(sales.max())
print(sales.sum())

600
1550

In [ ]:
import time
import numpy as np

# 1. Clear the overridden built-in if it exists in the current namespace
if 'list' in locals() or 'list' in globals():
    try:
        del list  # Removes your custom 'list' variable so Python uses the built-in function
    except NameError:
        pass

# Set the size of the collections
ELEMENT_COUNT = 1_000_000

print(f"Comparing performance using {ELEMENT_COUNT:,} elements...\n")

# --- PERFORMANCE TEST FOR PYTHON LIST ---
# Using list comprehension directly avoids relying on the list() constructor entirely
list_a = [i for i in range(ELEMENT_COUNT)]
list_b = [i for i in range(ELEMENT_COUNT)]

start_list_time = time.perf_counter()
list_result = [x + y for x, y in zip(list_a, list_b)]
end_list_time = time.perf_counter()

list_duration = end_list_time - start_list_time
print(f"Python List Execution Time: {list_duration:.6f} seconds")


# --- PERFORMANCE TEST FOR NUMPY ARRAY ---
array_a = np.arange(ELEMENT_COUNT)
array_b = np.arange(ELEMENT_COUNT)

start_array_time = time.perf_counter()
array_result = array_a + array_b
end_array_time = time.perf_counter()

array_duration = end_array_time - start_array_time
print(f"NumPy Array Execution Time: {array_duration:.6f} seconds")


# --- FINAL COMPARISON ---
speed_difference = list_duration / array_duration
print("-" * 45)
print(f"NumPy Array is roughly {speed_difference:.1f}x faster than a Python List.")
print("-" * 45)

Comparing performance using 1,000,000 elements...

Python List Execution Time: 0.040903 seconds
NumPy Array Execution Time: 0.001761 seconds
---------------------------------------------
NumPy Array is roughly 23.2x faster than a Python List.
---------------------------------------------

In [ ]:
#1d array
a=np.array([10,20,30])
print(a)

[10 20 30]

In [ ]:
a=np.array([10,20,30])
a.shape

(3,)

In [ ]:
a.size

3

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [ ]:
# 3D Array
c = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("\n3D Array:")
print(c)
print("Shape of 3D Array:", c.shape)

In [ ]:
a.sha

(3,)

In [ ]:
def num():
  yield 1
  yield 2
  yield 3
g=num()
print(next(g))
print(next(g))
print(next(g))

1
2
3

In [ ]:
import pandas as pd

data = {
    "name": ['manoj', 'rohit', 'sachin'],
    "age": [12, 13, 14],
    "city": ['bengalore', 'chennai', 'pune']
}

df = pd.DataFrame(data)

print(df)

     name  age       city
0   manoj   12  bengalore
1   rohit   13    chennai
2  sachin   14       pune

In [6]:
import pandas as pd
df=pd.read_csv('/content/data.csv')
df
df.columns
df.shape
df.dtypes

Date         object
Category     object
Value       float64
Product      object
Sales       float64
Region       object
dtype: object

In [ ]:
df.describe()

           Value       Sales
count  47.000000   46.000000
mean   51.744681  557.130435
std    29.050532  274.598584
min     2.000000  108.000000
25%    27.500000  339.000000
50%    54.000000  591.500000
75%    70.000000  767.500000
max    99.000000  992.000000

In [ ]:
df.isnull().sum()

Date        0
Category    0
Value       3
Product     0
Sales       4
Region      0
dtype: int64

In [ ]:
print(df["Sales"])

0     754.0
1     110.0
2     398.0
3     522.0
4     869.0
5     192.0
6     936.0
7     488.0
8     772.0
9     834.0
10    842.0
11      0.0
12    628.0
13    423.0
14    893.0
15    895.0
16    511.0
17    108.0
18    578.0
19    736.0
20    606.0
21    992.0
22    942.0
23    342.0
24    458.0
25    584.0
26    619.0
27    224.0
28    617.0
29    737.0
30    735.0
31    189.0
32    338.0
33      0.0
34    669.0
35      0.0
36    177.0
37      0.0
38    408.0
39    155.0
40    578.0
41    256.0
42    164.0
43    949.0
44    830.0
45    599.0
46    938.0
47    143.0
48    182.0
49    708.0
Name: Sales, dtype: float64

In [ ]:
df = df.fillna(0)

In [ ]:
print(df)

          Date Category  Value   Product  Sales Region
0   2023-01-01        A   28.0  Product1  754.0   East
1   2023-01-02        B   39.0  Product3  110.0  North
2   2023-01-03        C   32.0  Product2  398.0   East
3   2023-01-04        B    8.0  Product1  522.0   East
4   2023-01-05        B   26.0  Product3  869.0  North
5   2023-01-06        B   54.0  Product3  192.0   West
6   2023-01-07        A   16.0  Product1  936.0   East
7   2023-01-08        C   89.0  Product1  488.0   West
8   2023-01-09        C   37.0  Product3  772.0   West
9   2023-01-10        A   22.0  Product2  834.0   West
10  2023-01-11        B    7.0  Product1  842.0  North
11  2023-01-12        B   60.0  Product2    0.0   West
12  2023-01-13        A   70.0  Product3  628.0  South
13  2023-01-14        A   69.0  Product1  423.0   East
14  2023-01-15        A   47.0  Product2  893.0   West
15  2023-01-16        C    0.0  Product1  895.0  North
16  2023-01-17        C   93.0  Product2  511.0  South
17  2023-01-18        C    0.0  Product1  108.0   West
18  2023-01-19        A   31.0  Product2  578.0   West
19  2023-01-20        A   59.0  Product1  736.0   East
20  2023-01-21        C   82.0  Product3  606.0  South
21  2023-01-22        C   37.0  Product2  992.0  South
22  2023-01-23        B   62.0  Product3  942.0  North
23  2023-01-24        C   92.0  Product2  342.0   West
24  2023-01-25        A   24.0  Product2  458.0   East
25  2023-01-26        C   95.0  Product1  584.0   West
26  2023-01-27        C   71.0  Product2  619.0  North
27  2023-01-28        C   56.0  Product2  224.0  North
28  2023-01-29        B    0.0  Product3  617.0  North
29  2023-01-30        C   51.0  Product2  737.0  South
30  2023-01-31        B   50.0  Product3  735.0   West
31  2023-02-01        A   17.0  Product2  189.0   West
32  2023-02-02        B   63.0  Product3  338.0  South
33  2023-02-03        C   27.0  Product3    0.0   East
34  2023-02-04        C   70.0  Product3  669.0   West
35  2023-02-05        B   60.0  Product2    0.0   West
36  2023-02-06        C   36.0  Product3  177.0   East
37  2023-02-07        C    2.0  Product1    0.0  North
38  2023-02-08        C   94.0  Product1  408.0  South
39  2023-02-09        A   62.0  Product1  155.0   West
40  2023-02-10        B   15.0  Product1  578.0   East
41  2023-02-11        C   97.0  Product1  256.0   East
42  2023-02-12        A   93.0  Product3  164.0   West
43  2023-02-13        A   43.0  Product3  949.0   East
44  2023-02-14        A   96.0  Product3  830.0   East
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [ ]:
df.isnull().sum()

Date        0
Category    0
Value       0
Product     0
Sales       0
Region      0
dtype: int64

In [ ]:
df.rename(columns={'Date':'Sales Date'})

    Sales Date Category  Value   Product  Sales Region
0   2023-01-01        A   28.0  Product1  754.0   East
1   2023-01-02        B   39.0  Product3  110.0  North
2   2023-01-03        C   32.0  Product2  398.0   East
3   2023-01-04        B    8.0  Product1  522.0   East
4   2023-01-05        B   26.0  Product3  869.0  North
5   2023-01-06        B   54.0  Product3  192.0   West
6   2023-01-07        A   16.0  Product1  936.0   East
7   2023-01-08        C   89.0  Product1  488.0   West
8   2023-01-09        C   37.0  Product3  772.0   West
9   2023-01-10        A   22.0  Product2  834.0   West
10  2023-01-11        B    7.0  Product1  842.0  North
11  2023-01-12        B   60.0  Product2    0.0   West
12  2023-01-13        A   70.0  Product3  628.0  South
13  2023-01-14        A   69.0  Product1  423.0   East
14  2023-01-15        A   47.0  Product2  893.0   West
15  2023-01-16        C    0.0  Product1  895.0  North
16  2023-01-17        C   93.0  Product2  511.0  South
17  2023-01-18        C    0.0  Product1  108.0   West
18  2023-01-19        A   31.0  Product2  578.0   West
19  2023-01-20        A   59.0  Product1  736.0   East
20  2023-01-21        C   82.0  Product3  606.0  South
21  2023-01-22        C   37.0  Product2  992.0  South
22  2023-01-23        B   62.0  Product3  942.0  North
23  2023-01-24        C   92.0  Product2  342.0   West
24  2023-01-25        A   24.0  Product2  458.0   East
25  2023-01-26        C   95.0  Product1  584.0   West
26  2023-01-27        C   71.0  Product2  619.0  North
27  2023-01-28        C   56.0  Product2  224.0  North
28  2023-01-29        B    0.0  Product3  617.0  North
29  2023-01-30        C   51.0  Product2  737.0  South
30  2023-01-31        B   50.0  Product3  735.0   West
31  2023-02-01        A   17.0  Product2  189.0   West
32  2023-02-02        B   63.0  Product3  338.0  South
33  2023-02-03        C   27.0  Product3    0.0   East
34  2023-02-04        C   70.0  Product3  669.0   West
35  2023-02-05        B   60.0  Product2    0.0   West
36  2023-02-06        C   36.0  Product3  177.0   East
37  2023-02-07        C    2.0  Product1    0.0  North
38  2023-02-08        C   94.0  Product1  408.0  South
39  2023-02-09        A   62.0  Product1  155.0   West
40  2023-02-10        B   15.0  Product1  578.0   East
41  2023-02-11        C   97.0  Product1  256.0   East
42  2023-02-12        A   93.0  Product3  164.0   West
43  2023-02-13        A   43.0  Product3  949.0   East
44  2023-02-14        A   96.0  Product3  830.0   East
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [7]:
df.head()

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North

In [ ]:
def square(x):
  return x**2
square(8)

64

In [ ]:
a=lambda x:x**2
print(a(8))

64

In [ ]:
df['Value'].apply(lambda x:x**2)

0      784.0
1     1521.0
2     1024.0
3       64.0
4      676.0
5     2916.0
6      256.0
7     7921.0
8     1369.0
9      484.0
10      49.0
11    3600.0
12    4900.0
13    4761.0
14    2209.0
15       0.0
16    8649.0
17       0.0
18     961.0
19    3481.0
20    6724.0
21    1369.0
22    3844.0
23    8464.0
24     576.0
25    9025.0
26    5041.0
27    3136.0
28       0.0
29    2601.0
30    2500.0
31     289.0
32    3969.0
33     729.0
34    4900.0
35    3600.0
36    1296.0
37       4.0
38    8836.0
39    3844.0
40     225.0
41    9409.0
42    8649.0
43    1849.0
44    9216.0
45    9801.0
46      36.0
47    4761.0
48    4225.0
49     121.0
Name: Value, dtype: float64

In [ ]:
df['Value'].apply(lambda x:x+x)

0      56.0
1      78.0
2      64.0
3      16.0
4      52.0
5     108.0
6      32.0
7     178.0
8      74.0
9      44.0
10     14.0
11    120.0
12    140.0
13    138.0
14     94.0
15      0.0
16    186.0
17      0.0
18     62.0
19    118.0
20    164.0
21     74.0
22    124.0
23    184.0
24     48.0
25    190.0
26    142.0
27    112.0
28      0.0
29    102.0
30    100.0
31     34.0
32    126.0
33     54.0
34    140.0
35    120.0
36     72.0
37      4.0
38    188.0
39    124.0
40     30.0
41    194.0
42    186.0
43     86.0
44    192.0
45    198.0
46     12.0
47    138.0
48    130.0
49     22.0
Name: Value, dtype: float64

In [8]:
df.head()

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North

In [9]:
def convert_vijay(x):
  return x.lower()

In [10]:
df['Region'].apply(convert_vijay)

0      east
1     north
2      east
3      east
4     north
5      west
6      east
7      west
8      west
9      west
10    north
11     west
12    south
13     east
14     west
15    north
16    south
17     west
18     west
19     east
20    south
21    south
22    north
23     west
24     east
25     west
26    north
27    north
28    north
29    south
30     west
31     west
32    south
33     east
34     west
35     west
36     east
37    north
38    south
39     west
40     east
41     east
42     west
43     east
44     east
45     west
46    south
47     west
48    north
49    north
Name: Region, dtype: object

In [12]:
df['Region'].apply(lambda x:x.lower())

0      east
1     north
2      east
3      east
4     north
5      west
6      east
7      west
8      west
9      west
10    north
11     west
12    south
13     east
14     west
15    north
16    south
17     west
18     west
19     east
20    south
21    south
22    north
23     west
24     east
25     west
26    north
27    north
28    north
29    south
30     west
31     west
32    south
33     east
34     west
35     west
36     east
37    north
38    south
39     west
40     east
41     east
42     west
43     east
44     east
45     west
46    south
47     west
48    north
49    north
Name: Region, dtype: object

In [14]:
pd.to_datetime(df['Date'])

0    2023-01-01
1    2023-01-02
2    2023-01-03
3    2023-01-04
4    2023-01-05
5    2023-01-06
6    2023-01-07
7    2023-01-08
8    2023-01-09
9    2023-01-10
10   2023-01-11
11   2023-01-12
12   2023-01-13
13   2023-01-14
14   2023-01-15
15   2023-01-16
16   2023-01-17
17   2023-01-18
18   2023-01-19
19   2023-01-20
20   2023-01-21
21   2023-01-22
22   2023-01-23
23   2023-01-24
24   2023-01-25
25   2023-01-26
26   2023-01-27
27   2023-01-28
28   2023-01-29
29   2023-01-30
30   2023-01-31
31   2023-02-01
32   2023-02-02
33   2023-02-03
34   2023-02-04
35   2023-02-05
36   2023-02-06
37   2023-02-07
38   2023-02-08
39   2023-02-09
40   2023-02-10
41   2023-02-11
42   2023-02-12
43   2023-02-13
44   2023-02-14
45   2023-02-15
46   2023-02-16
47   2023-02-17
48   2023-02-18
49   2023-02-19
Name: Date, dtype: datetime64[ns]

In [18]:
df['Date']

0     2023-01-01
1     2023-01-02
2     2023-01-03
3     2023-01-04
4     2023-01-05
5     2023-01-06
6     2023-01-07
7     2023-01-08
8     2023-01-09
9     2023-01-10
10    2023-01-11
11    2023-01-12
12    2023-01-13
13    2023-01-14
14    2023-01-15
15    2023-01-16
16    2023-01-17
17    2023-01-18
18    2023-01-19
19    2023-01-20
20    2023-01-21
21    2023-01-22
22    2023-01-23
23    2023-01-24
24    2023-01-25
25    2023-01-26
26    2023-01-27
27    2023-01-28
28    2023-01-29
29    2023-01-30
30    2023-01-31
31    2023-02-01
32    2023-02-02
33    2023-02-03
34    2023-02-04
35    2023-02-05
36    2023-02-06
37    2023-02-07
38    2023-02-08
39    2023-02-09
40    2023-02-10
41    2023-02-11
42    2023-02-12
43    2023-02-13
44    2023-02-14
45    2023-02-15
46    2023-02-16
47    2023-02-17
48    2023-02-18
49    2023-02-19
Name: Date, dtype: object

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      50 non-null     object
 1   Category  50 non-null     object
 2   Value     47 non-null     float64
 3   Product   50 non-null     object
 4   Sales     46 non-null     float64
 5   Region    50 non-null     object
dtypes: float64(2), object(4)
memory usage: 2.5+ KB

In [20]:
df['Date']=pd.to_datetime(df['Date'])

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      50 non-null     datetime64[ns]
 1   Category  50 non-null     object
 2   Value     47 non-null     float64
 3   Product   50 non-null     object
 4   Sales     46 non-null     float64
 5   Region    50 non-null     object
dtypes: datetime64[ns](1), float64(2), object(3)
memory usage: 2.5+ KB

In [22]:
df.to_csv("cleaned_date.csv")